---
- include: percona-repo.yml

- hosts: small-nodes
  vars:
    mysql_version: 5.5
  sudo: yes
  tasks:
  - name: Install Percona Server
    apt: name={{ item }} state=present
    with_items:
      - percona-server-server-{{ mysql_version }}
      - python-mysqldb 
    notify:
    - mysql running
  - name: Set root password
    mysql_user: host={{ item }} login_user=root login_password='' name=nagios password=toor priv=*.*:"PROCESS,SUPER,REPLICATION CLIENT" state=present
    with_items:
      - 'localhost'
      - '127.0.0.1'
      - '%'
    notify:
    - mysql running

  handlers:
  - name: mysql running
    service: name=mysql state=started
