---
- hosts: monitor-server
  tasks:
  - name: Fake task to get facts
    service: name={{ item }} state=present
    with_items:
    - []

- hosts: small-nodes
  vars:
  - username: nagios
  sudo: yes
  tasks:
  - name: Install needed packages --> nagios-plugins, nagios-nrpe-server, percona nagios plugins
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
    with_items:
      - nagios-plugins
      - nagios-nrpe-server
      - percona-nagios-plugins

  - name: Add local ip to allowed_hosts on /etc/nagios/nrpe.cfg
    lineinfile: dest=/etc/nagios/nrpe.cfg regexp='^allowed_hosts.*' line='allowed_hosts=127.0.0.1,{{ ansible_eth1.ipv4.address }},{{ hostvars[groups['monitor-server'][0]]['ansible_eth1']['ipv4']['address'] }}' state=present
    notify: 
    - restart nagios nrpe

  - name: Comment default hardcoded commands present inside nrpe.cfg
    replace: dest=/etc/nagios/nrpe.cfg regexp='^command\[' replace='# \g<0>'

  - name: Give sudo passwordless to nagios
    template: src=../templates/sudoers.j2 dest=/etc/sudoers.d/{{ username }} owner=root
      group=root mode=0440 validate='visudo -cf %s'

  handlers:
  - name: restart nagios nrpe
    service: name=nagios-nrpe-server state=restarted
    when: "'small-nodes' in {{ group_names }}"
